# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.
options:
  tls-secret-name:
    default: ""
    description: The name of the Kubernetes secret used to get the TLS certificate used for HTTPS. This settings overrides any tls-certificate relation defined. If left empty and no tls-certificates relation is defined, the charm will block until TLS is configured.
    type: string
  service-hostname:
    default: ""
    description: The hostname of the service to create an ingress for.
    type: string