# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.
options:
  external-hostname:
    default: ""
    description: The hostname of the ingress.
    type: string
  gateway-class:
    default: ""
    description: The gateway class.
    type: string
