name: RTD workflows

on:
  pull_request:

jobs:
  rtd-docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs_rtd.yaml@1e2cab8312dc6e0b8da15f78f098c61b50b5fd73  # main
    secrets: inherit
    with:
      enable-sphinx-python-dependency-build-checks: false
      python-version: '3.12'
