# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Tag product Terraform module

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/product/VERSION'

jobs:
  tag:
    uses: ./.github/workflows/tag_terraform_module.yaml
    permissions:
      contents: write
    with:
      module-directory: terraform/product
      tag-prefix: tf-gateway-api-integrator-product
